### ISSUE TITLE
README 자동화

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/presentation-en#5]
멤버 테이블 생성 자동화가 되면 좋겠습니다.. 
특히 이미지!

**Comment by AnneMayor** [comment]
@all contributors 봇 이라는 앱을 찾아봤는데 이게 풀리퀘나 issue에 명령어로 추가해달라고 하면 자동으로 README.md 에 contributors 리스트 생성해주는 기능인 것 같아요 제가 저희 그룹에다 github app 설치하고 가이드대로 해봤는데 적용이 되고 있지 않은 것 같아서요 그룹 생성자님이 혹시 가이드 보시고 하셨을 때 어떤지좀 공유해주시면 감사하겠습니다

**Comment by AnneMayor** [comment]
@ALL 이슈 해결 완료하였습니다!페이지 다음과 같이 수정하니 참고하세요~!!!
