### ISSUE TITLE
2022 Season 1(2021.12 ~ 2022.02)

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/presentation-en#60]
### 2021.12.29 OT
[Chat 🗯](https://github.com/ready-techie/presentation-en/wiki/2021-12-29)
<br />

### 2022.01.05 Presentation 
- [Speaker: Anne, Bin](https://github.com/ready-techie/presentation-en/wiki/2022-01-05)
### 2022.01.12 Presentation 
- [Speaker: Nicky](https://github.com/ready-techie/presentation-en/wiki/2022-01-12)
### 2022.01.19 Presentation 
- [Speaker: Nicky](https://github.com/ready-techie/presentation-en/wiki/2022-01-19)
### 2022.01.26 Presentation 
- [Speaker: Toru, Anne](https://github.com/ready-techie/presentation-en/wiki/2022-01-26)

`Anne can do anytime`

### 2022.02.09 Discussion

**Comment by TORU0239** [comment]
Confirmed. :)

**Comment by AnneMayor** [comment]
Checked it. I will do my best to present as many as possible 😄

**Comment by wooooooood** [comment]
Issued my personal sprint for this seasonnnnnn
https://github.com/ready-techie/weekly-retrospective/issues/44
