### ISSUE TITLE
2022 Season 2(2022.02 ~ 2022.03)

### ISSUE THREAD

**Issue by wooooooood** [ready-techie/presentation-en#67]
Along with new members!

### 2022.02.23 OT
[Chat 🗯](https://github.com/ready-techie/presentation-en/wiki/2022-02-24-%F0%9F%8E%89OT)
<br />

### 2022.03.02 Presentation 
- Bin, Mason
### 2022.03.09 Presentation 
- [Dragon, Anne](https://github.com/ready-techie/presentation-en/wiki/2022-03-09)
### 2022.03.16 Presentation 
- Anne, Bin, Mason
### 2022.03.23 Presentation 
- Dragon, Nicky, Toru, Aragon

`Aragon can do anytime`

### 2022.03.30 Discussion

**Comment by 0417taehyun** [comment]
@wooooooood , @AnneMayor 

Can you add me on March 9th and 23rd?

**Comment by AnneMayor** [comment]
@0417taehyun Sure. No problem. Will add you at the day you want.
